name: tetris-deep-q-learning
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy>=1.23
  - jupyter
  - pip
  - pytorch
  - tensorboard
  - pip:
    - gym[classic_control]>=0.26
    - scipy
    - tqdm
    - wheel
    - matplotlib




